// <auto-generated />
using System;
using WebApplication1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20191114194232_Schools")]
    partial class Schools
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.School.School", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("abr_nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("blog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cat_part_comunitaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cat_part_confessional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cat_part_filantropica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cat_part_privada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cep")
                        .HasColumnType("int");

                    b.Property<string>("convenio_estadual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("convenio_fasc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("convenio_federal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("convenio_municipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data_extracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("dep_administrativa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("desc_reg_conselho_tutelar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("desc_reg_orcamento_part")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("escola_especial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("inep")
                        .HasColumnType("int");

                    b.Property<float>("latitude")
                        .HasColumnType("real");

                    b.Property<string>("logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("longitude")
                        .HasColumnType("real");

                    b.Property<string>("mant_apae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mant_empresa_privada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mant_ong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mant_sindicato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mant_sistema_s")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<int>("reg_conselho_tutelar")
                        .HasColumnType("int");

                    b.Property<int>("reg_orcamento_part")
                        .HasColumnType("int");

                    b.Property<string>("situacao_funcionamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url_website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Schools");
                });
#pragma warning restore 612, 618
        }
    }
}
